query latestPost {
  posts(first: 1, orderBy: publishedAt_DESC) {
    title
    id
    slug
    author {
      name
      title
      picture {
        altText
        authorAvatar {
          picture {
            fileName
            height
            size
            url
            width
          }
        }
      }
    }
    content {
      html
      json
      markdown
      text
    }
    coverImage {
      height
      id
      size
      url
      width
    }
  }
}
