query allPosts(
  $orderBy: PostOrderByInput
  $first: Int
  $skip: Int
  $where: PostWhereInput
) {
  posts(orderBy: $orderBy, first: $first, skip: $skip, where: $where) {
    id
    title
    slug
    excerpt
    date
    coverImage {
      id
      url
    }
    content {
      text
    }
    author {
      id
    }
  }
}
